version: "3"

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

services:
  portfolio:
    image: djangoreactdev/portfolio:1.3

  portfolio-sanity:
    image: djangoreactdev/portfolio-sanity:1.3

  wow-effecting:
    image: djangoreactdev/wow-effecting:1.0

################################Cosmetic##################################

  cosmetic-api:
    image: djangoreactdev/cosmetic-api:1.0
    depends_on:
      - postgres
      - redis
    env_file:
      - ./cosmetic/.envs/.production/.django
      - ./cosmetic/.envs/.production/.postgres
    command: /cosmetic/compose/production/django/start

  postgres:
    build:
      context: ./cosmetic
      dockerfile: ./compose/production/postgres/Dockerfile
    image: cosmetic_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./cosmetic/.envs/.production/.postgres

  awscli:
    build:
      context: ./cosmetic
      dockerfile: ./compose/production/aws/Dockerfile
    image: awscli
    env_file:
      - ./cosmetic/.envs/.production/.django
    volumes:
      - production_postgres_data_backups:/backups:z

  redis:
    image: redis:6

  cosmetic-front:
    image: djangoreactdev/cosmetic-front:1.0
    # volumes:
    #   - ./front-next:/app
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - cosmetic-api
    environment:
      NODE_ENV: production
    # user: root

  cosmetic-dashboard:
    image: djangoreactdev/cosmetic-dashboard:1.0
    # volumes:
    #   - ./dashboard-next:/app
    command: npm start
    ports:
      - "9000:9000"
    depends_on:
      - cosmetic-api
    environment:
      NODE_ENV: production
    # user: root

################################Codehelp##################################


  traefik:
    build:
      context: .
      dockerfile: ./traefik/Dockerfile
    image: production_traefik:1.1
    depends_on:
      - portfolio
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
