version: "3"

volumes:
  production_traefik: {}

services:
  portfolio:
    image: djangoreactdev/portfolio:latest

  portfolio-sanity:
    image: djangoreactdev/portfolio-sanity:latest

  cosmetic:
    image: djangoreactdev/cosmetic:latest

  wow-effecting:
    image: djangoreactdev/wow-effecting:latest

  codehelp:
    image: djangoreactdev/codehelp:latest

  traefik:
    image: production_traefik:latest
    depends_on:
      - portfolio
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
