version: "3.8"

services:
  web:
    build:
      context: ./back
      dockerfile: Dockerfile
    command: gunicorn core_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 8000:8000
    env_file:
      - ./.envs/.env
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.envs/.env.db

  # nginx:
  #   build: ./nginx
  #   volumes:
  #     - static_volume:/home/app/web/staticfiles
  #     - media_volume:/home/app/web/mediafiles
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - web

  # front:
  #   container_name: react-datta
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   volumes:
  #     - '.:/app'
  #     - '/app/node_modules'
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
      

volumes:
  postgres_data:
  static_volume:
  media_volume: