version: "3"

volumes:
  production_traefik: {}

services:
  portfolio:
    image: djangoreactdev/portfolio:1.3

  portfolio-sanity:
    image: djangoreactdev/portfolio-sanity:1.3

  cosmetic-api:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: cosmetic-api:1.0.1
    container_name: cosmetic-api
    depends_on:
      - postgres
      - redis
    env_file:
      - ./cosmetic/.envs/.production/.django
      - ./cosmetic.envs/.production/.postgres
    command: /cosmetic/compose/production/django/start



  wow-effecting:
    image: djangoreactdev/wow-effecting:1.0

  # codehelp:
  #   image: djangoreactdev/codehelp:1.0
  #   env_file:
  #     - ./.envs/.env
  #   depends_on:
  #     - db
      
  # db:
  #   image: postgres:13.0-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   env_file:
  #     - ./.envs/.env.db

  traefik:
    image: production_traefik:1.1
    depends_on:
      - portfolio
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
