log:
  level: INFO

entryPoints:
  web:
    # http
    address: ":80"
    http:
      # https://docs.traefik.io/routing/entrypoints/#entrypoint
      redirections:
        entryPoint:
          to: web-secure

  web-secure:
    # https
    address: ":443"

certificatesResolvers:
  letsencrypt:
    # https://docs.traefik.io/master/https/acme/#lets-encrypt
    acme:
      email: "djangoreactdev@gmail.com"
      storage: /etc/traefik/acme/acme.json
      # https://docs.traefik.io/master/https/acme/#httpchallenge
      httpChallenge:
        entryPoint: web

http:
  routers:
    portfolio-router:
      rule: "Host(`solovkadmytro.pp.ua`) || Host(`www.solovkadmytro.pp.ua`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: portfolio
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    portfolio-sanity-router:
      rule: "Host(`dush.solovkadmytro.pp.ua`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: portfolio-sanity
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt
##############################  cosmetic  ########################
    cosmetic-front-router:
      rule: "Host(`cosmeticpro.pp.ua`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: cosmetic-front
      tls:
        certResolver: letsencrypt

    cosmetic-api-router:
      rule: "Host(`api.cosmeticpro.pp.ua`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: cosmetic-api
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

    cosmetic-dashboard-router:
      rule: "Host(`dashboard.cosmeticpro.pp.ua`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: cosmetic-dashboard
      tls:
        # https://docs.traefik.io/master/routing/routers/#certresolver
        certResolver: letsencrypt

###################### end cosmetic ########################


    wow-effecting-router:
      rule: "Host(`liveisgood.pp.ua`) || Host(`www.liveisgood.pp.ua`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: wow-effecting
      tls:
        certResolver: letsencrypt

    codehelp-router:
      rule: "Host(`my.codehelp.pp.ua`) || Host(`www.logod.pp.ua`)|| Host(`logod.pp.ua`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: codehelp
      tls:
        certResolver: letsencrypt

    my-codehelp-router:
      rule: "Host(`my.codehelp.pp.ua`)"
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: codehelp
      tls:
        certResolver: letsencrypt

  middlewares:
    csrf:
      # https://docs.traefik.io/master/middlewares/headers/#hostsproxyheaders
      # https://docs.djangoproject.com/en/dev/ref/csrf/#ajax
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    portfolio:
      loadBalancer:
        servers:
          - url: http://portfolio:3000

    portfolio-sanity:
      loadBalancer:
        servers:
          - url: http://portfolio-sanity:3333

    cosmetic:
      loadBalancer:
        servers:
          - url: http://cosmetic:3000

    wow-effecting:
      loadBalancer:
        servers:
          - url: http://wow-effecting:3000

    codehelp:
      loadBalancer:
        servers:
          - url: http://codehelp:3000

##############################  cosmetic  ########################

    cosmetic-dashboard:
      loadBalancer:
        servers:
          - url: http://cosmetic-dashboard:3000

    cosmetic-api:
      loadBalancer:
        servers:
          - url: http://cosmetic-api:5000

    cosmetic-front:
      loadBalancer:
        servers:
          - url: http://cosmetic-front:3000

providers:
  # https://docs.traefik.io/master/providers/file/
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
